### ISSUE TITLE
Get list of files that were changed since last step

### ISSUE THREAD

**Issue by belljustin** [ECSE456-G29/Untitled#10]
Create a function that returns a list of files that were "touched" (i.e. changed, added, deleted) since the last step

**Comment by belljustin** [comment]
[Here's](https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/ShowChangedFilesBetweenCommits.java) a recipe for listing the diff files between two commits

**Comment by abdelkoumare** [comment]
The function signature : 
Return : Either a list of file names or a collection or set. 
Add the function in repo.

**Comment by belljustin** [comment]
`public Set<String> diffSinceTag(String tagName)`

gets the set of filenames that were changed since the commit tagged with `tagName`

### Input:
- `tagName`: get diff since this name

### Output:
- set of filenames that have been changed since the tagged commit
