### ISSUE TITLE
Create a function that lists files changed in step AsciiDocs

### ISSUE THREAD

**Issue by belljustin** [ECSE456-G29/Untitled#11]
Create a function that parses an AsciiDoc step and lists all files that were "touched" (i.e. edited, added, deleted) in the text

**Comment by abdelkoumare** [comment]
Write the code in a new file.  -- Just will create the file where it needs to go to

**Comment by Ryan-Chalmers** [comment]
we need to decide what our asciidoc files are going to look like, currently i am using WARNING: to show that a file has been changed in a step and parsing it using that but it can def be changed

**Comment by Ryan-Chalmers** [comment]
Works for "WARNING: /abs/file/path Has been changed!"
