### ISSUE TITLE
Initialize repo with empty AsciiDoc

### ISSUE THREAD

**Issue by puranik9** [ECSE456-G29/Untitled#8]
Whenever `g2t init` is run, we would like the repo to be initialized with an empty AsciiDoc.

**Comment by Ryan-Chalmers** [comment]
this is done under branch Issue8 if someone wants to give it a look before I close it

**Comment by Ryan-Chalmers** [comment]
oh lol I didnt even notice kartik had put this into in progress... just understanding how this workflow stuff works on git

**Comment by puranik9** [comment]
Things look good here, although I pulled the branch and when I ran `g2t init`, it initiated an empty repo but it didn't create the asciidoc there. Maybe it's just me, but if when you tested it worked properly, create the PR and we'll merge it

**Comment by Ryan-Chalmers** [comment]
hey I just retried this and it creates the asciidoc, did you recreate the g2t distribution and install it?
